name: wacv_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3
  - pytorch
  - torchvision==0.13.0
  - scipy
  - scikit-image
  - scikit-learn
  - segmentation-models-pytorch
  - tqdm
  - seaborn
  - torchmetrics
  - opencv
